name: Code style

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
      - name: Install dependencies
        run: composer install
      - name: Run PHP CS Fixer
        run: composer run cs
      - name: Check EditorConfig configuration
        run: test -f .editorconfig
      - name: Check adherence to EditorConfig
        uses: greut/eclint-action@v0
